--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28/01/2021 21:14:29
-- Server version: 5.5.5-10.4.11-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE vpn;

--
-- Drop table `tblasistenciaxcelebracion`
--
DROP TABLE IF EXISTS tblasistenciaxcelebracion;

--
-- Drop procedure `spCelebraciones_Actualizar`
--
DROP PROCEDURE IF EXISTS spCelebraciones_Actualizar;

--
-- Drop procedure `spCelebraciones_ConsultarDisponibilidad`
--
DROP PROCEDURE IF EXISTS spCelebraciones_ConsultarDisponibilidad;

--
-- Drop procedure `spCelebraciones_LlenarMaestro`
--
DROP PROCEDURE IF EXISTS spCelebraciones_LlenarMaestro;

--
-- Drop procedure `spMiembros_Consultar`
--
DROP PROCEDURE IF EXISTS spMiembros_Consultar;

--
-- Drop table `tblcelebraciones`
--
DROP TABLE IF EXISTS tblcelebraciones;

--
-- Drop procedure `spMiembros_Actualizar`
--
DROP PROCEDURE IF EXISTS spMiembros_Actualizar;

--
-- Drop procedure `spMiembros_Guardar`
--
DROP PROCEDURE IF EXISTS spMiembros_Guardar;

--
-- Drop table `tbl_miembros`
--
DROP TABLE IF EXISTS tbl_miembros;

--
-- Set default database
--
USE vpn;

--
-- Create table `tbl_miembros`
--
CREATE TABLE tbl_miembros (
  MiembroID INT(11) NOT NULL AUTO_INCREMENT,
  CelebracionID INT(11) DEFAULT NULL,
  Cedula INT(11) NOT NULL,
  Nombre VARCHAR(255) DEFAULT NULL,
  Edad INT(11) DEFAULT NULL,
  Celular VARCHAR(255) NOT NULL DEFAULT '',
  Correo VARCHAR(255) NOT NULL DEFAULT '',
  TipoMiembro INT(11) NOT NULL,
  SintomasCovid INT(11) NOT NULL,
  Temperatura INT(11) NOT NULL,
  Consentimiento BIT(1) DEFAULT NULL,
  Fecha DATE DEFAULT NULL,
  Estado BIT(1) DEFAULT NULL,
  PRIMARY KEY (MiembroID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 13,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

DELIMITER $$

--
-- Create procedure `spMiembros_Guardar`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spMiembros_Guardar(IN pCelebracionID INT, IN pCedula INT, IN pNombre VARCHAR(255), IN pEdad INT, IN pCelular VARCHAR(255), IN pCorreo VARCHAR(255), IN pTipoMiembro INT, IN pSintomasCovid INT, IN pConsentimiento BIT, IN pFecha DATE)
BEGIN

declare pID INT ;

INSERT INTO tbl_miembros (CelebracionID, Cedula, Nombre, Edad, Celular, Correo, TipoMiembro, SintomasCovid, Consentimiento, Fecha)
  VALUES (pCelebracionID, pCedula, pNombre, pEdad, pCelular, pCorreo, pTipoMiembro, pSintomasCovid, pConsentimiento, pFecha);

  SET pID= LAST_INSERT_ID();


SELECT
  pID;
END
$$

--
-- Create procedure `spMiembros_Actualizar`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spMiembros_Actualizar(IN pMiembroID INT, IN pTemperatura VARCHAR(255), IN pFechaUltimaActualizacion DATE)
BEGIN

UPDATE tbl_miembros
SET Temperatura = pTemperatura,
    Fecha = pFechaUltimaActualizacion
WHERE MiembroID = pMiembroID;

END
$$

DELIMITER ;

--
-- Create table `tblcelebraciones`
--
CREATE TABLE tblcelebraciones (
  CelebracionID INT(11) NOT NULL AUTO_INCREMENT,
  Fecha DATE DEFAULT NULL,
  Hora TIME DEFAULT NULL,
  Estado BIT(1) DEFAULT NULL,
  Usuario VARCHAR(255) DEFAULT NULL,
  Personas INT(11) NOT NULL,
  FechaActualizacion DATE DEFAULT NULL,
  Vigencia BIT(1) DEFAULT NULL,
  PRIMARY KEY (CelebracionID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

DELIMITER $$

--
-- Create procedure `spMiembros_Consultar`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spMiembros_Consultar(IN pNombre VARCHAR(255), IN pCedula VARCHAR(255))
BEGIN
set lc_time_names = 'es_ES';
 if pCedula != ''  then
SELECT
  tbl_miembros.MiembroID,
  tbl_miembros.Nombre,
  tbl_miembros.Cedula,
  CONCAT(DAYNAME(tblcelebraciones.Fecha), ' ', tblcelebraciones.Fecha, ' - ', TIME_FORMAT(tblcelebraciones.Hora, '%h:%i %p')) AS Celebracion,
  tbl_miembros.Fecha,
  tbl_miembros.Edad
FROM tbl_miembros
  INNER JOIN tblcelebraciones
    ON tbl_miembros.CelebracionID = tblcelebraciones.CelebracionID
WHERE Cedula LIKE CONCAT('%', pCedula, '%')
ORDER BY Fecha DESC LIMIT 10;
ELSE
SELECT
  tbl_miembros.MiembroID,
  tbl_miembros.Nombre,
  tbl_miembros.Cedula,
  CONCAT(DAYNAME(tblcelebraciones.Fecha), ' ', tblcelebraciones.Fecha, ' - ', TIME_FORMAT(tblcelebraciones.Hora, '%h:%i %p')) AS Celebracion,
  tbl_miembros.Fecha,
  tbl_miembros.Edad
FROM tbl_miembros
  INNER JOIN tblcelebraciones
    ON tbl_miembros.CelebracionID = tblcelebraciones.CelebracionID
WHERE Nombre LIKE CONCAT('%', pNombre, '%')
ORDER BY Fecha DESC LIMIT 10;
END IF;
END
$$

--
-- Create procedure `spCelebraciones_LlenarMaestro`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spCelebraciones_LlenarMaestro()
BEGIN
set lc_time_names = 'es_ES';

SELECT
  CelebracionID,
  CONCAT(DAYNAME(Fecha), ' ', Fecha, ' - ', TIME_FORMAT(Hora, '%h:%i %p')) AS Celebracion
FROM tblcelebraciones
WHERE Estado = 1;

END
$$

--
-- Create procedure `spCelebraciones_ConsultarDisponibilidad`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spCelebraciones_ConsultarDisponibilidad(IN pCelebracionId INT)
BEGIN


SELECT
  Personas AS Disponible
FROM tblcelebraciones
WHERE CelebracionID = pCelebracionId;
END
$$

--
-- Create procedure `spCelebraciones_Actualizar`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spCelebraciones_Actualizar(IN pCelebracionID INT, IN pPersonas INT)
BEGIN

if pPersonas > 0 then
UPDATE tblcelebraciones
SET Personas = Personas - 1
WHERE CelebracionID = pCelebracionID;
END IF;
END
$$

DELIMITER ;

--
-- Create table `tblasistenciaxcelebracion`
--
CREATE TABLE tblasistenciaxcelebracion (
  AsistenciaxcelebracionID INT(11) NOT NULL AUTO_INCREMENT,
  MiembroID INT(11) DEFAULT NULL,
  CelebracionID INT(11) DEFAULT NULL,
  Estado BIT(1) DEFAULT NULL,
  FechaUltimaActualizacion DATE DEFAULT NULL,
  PRIMARY KEY (AsistenciaxcelebracionID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table tbl_miembros
--
INSERT INTO tbl_miembros VALUES
(1, 1, 98712884, 'wilmar', 34, '', 'wilmargalvis@gmail.com', 0, 0, 52, True, '2021-01-02', True),
(2, 1, 98703362, 'norbey', 34, '', 'wilmargalvis@gmail.com', 0, 0, 0, False, '2021-01-11', True),
(4, 1, 1148, 'maria', 54, '', 'wilmargalvis@gmail.com', 0, 0, 35, True, '2021-01-25', True),
(5, 1, 98712884, 'wilmar', 34, '', 'wilmargalvis@gmail.com', 0, 0, 41, False, '2021-01-24', True),
(6, 1, 34, '43', 43, '', 'wilmargalvis@gmail.com', 0, 0, 43, True, '2021-01-23', True),
(7, 1, 1215, 'Monica Yepes', 59, '', 'wilmargalvis@gmail.com', 0, 0, 36, True, '2021-01-23', True),
(8, 1, 789456, 'angie', 15, '', 'wilmargalvis@gmail.com', 0, 0, 23, True, '2021-01-24', True),
(9, 1, 789456, 'angie', 15, '', 'wilmargalvis@gmail.com', 0, 0, 23, True, '2021-01-24', True),
(10, 1, 13579, 'Nelson', 32, '', 'wilmargalvis@gmail.com', 0, 0, 23, True, '2021-01-24', True),
(11, 1, 111222, 'Rosa de la Cruz', 0, '0', '0', 1, 1, 0, True, '2021-01-25', NULL),
(12, 1, 2112, 'SSS', 0, '0', '0', 1, 1, 0, True, '2021-01-28', NULL);

-- 
-- Dumping data for table tblcelebraciones
--
INSERT INTO tblcelebraciones VALUES
(1, '2021-01-17', '08:00:00', True, NULL, 7, NULL, NULL),
(2, '2021-01-17', '10:00:00', True, NULL, 2, NULL, NULL);

-- 
-- Dumping data for table tblasistenciaxcelebracion
--
-- Table vpn.tblasistenciaxcelebracion does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;